# Generated by Django 2.2.12 on 2025-05-03 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_auto_20250502_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='penerbit',
        ),
        migrations.AddField(
            model_name='buku',
            name='penerbit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Penerbit'),
        ),
        migrations.AddField(
            model_name='penerbit',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penerbit',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='nama',
            field=models.CharField(max_length=20),
        ),
    ]
