# Generated by Django 2.2.12 on 2025-05-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20250503_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
