# Generated by Django 2.2.12 on 2025-05-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_buku_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok_id',
            new_name='kelompok',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='penerbit_id',
            new_name='penerbit',
        ),
    ]
